-- Nifty 50 companies seed data

INSERT INTO public.companies (name, ticker, exchange, sector, industry) VALUES
('Adani Enterprises Limited',      'ADANIENT',    'NSE', 'Industrials',            'Diversified'),
('Adani Ports & SEZ Limited',      'ADANIPORTS',  'NSE', 'Industrials',            'Ports & Logistics'),
('Apollo Hospitals Enterprise',    'APOLLOHOSP',  'NSE', 'Healthcare',             'Hospitals'),
('Asian Paints Limited',           'ASIANPAINT',  'NSE', 'Consumer Staples',       'Paints'),
('Axis Bank Limited',              'AXISBANK',    'NSE', 'Banking',                'Private Sector Bank'),
('Bajaj Auto Limited',             'BAJAJ-AUTO',  'NSE', 'Automobiles',            'Two & Three Wheelers'),
('Bajaj Finance Limited',          'BAJFINANCE',  'NSE', 'Financial Services',     'NBFC'),
('Bajaj Finserv Limited',          'BAJAJFINSV',  'NSE', 'Financial Services',     'Insurance & Financing'),
('Bharat Electronics Limited',     'BEL',         'NSE', 'Industrials',            'Defence Electronics'),
('Bharti Airtel Limited',          'BHARTIARTL',  'NSE', 'Telecom',                'Mobile Services'),
('BPCL',                           'BPCL',        'NSE', 'Energy',                 'Oil Refining & Marketing'),
('Britannia Industries Limited',   'BRITANNIA',   'NSE', 'Consumer Staples',       'Food Products'),
('Cipla Limited',                  'CIPLA',       'NSE', 'Healthcare',             'Pharmaceuticals'),
('Coal India Limited',             'COALINDIA',   'NSE', 'Energy',                 'Coal Mining'),
('Dr. Reddy''s Laboratories',      'DRREDDY',     'NSE', 'Healthcare',             'Pharmaceuticals'),
('Eicher Motors Limited',          'EICHERMOT',   'NSE', 'Automobiles',            'Two Wheelers'),
('Grasim Industries Limited',      'GRASIM',      'NSE', 'Materials',              'Cement & Chemicals'),
('HCL Technologies Limited',       'HCLTECH',     'NSE', 'Information Technology', 'IT Services'),
('HDFC Bank Limited',              'HDFCBANK',    'NSE', 'Banking',                'Private Sector Bank'),
('HDFC Life Insurance Company',    'HDFCLIFE',    'NSE', 'Financial Services',     'Life Insurance'),
('Hero MotoCorp Limited',          'HEROMOTOCO',  'NSE', 'Automobiles',            'Two Wheelers'),
('Hindalco Industries Limited',    'HINDALCO',    'NSE', 'Materials',              'Aluminium'),
('Hindustan Unilever Limited',     'HINDUNILVR',  'NSE', 'Consumer Staples',       'FMCG'),
('ICICI Bank Limited',             'ICICIBANK',   'NSE', 'Banking',                'Private Sector Bank'),
('IndusInd Bank Limited',          'INDUSINDBK',  'NSE', 'Banking',                'Private Sector Bank'),
('Infosys Limited',                'INFY',        'NSE', 'Information Technology', 'IT Services'),
('ITC Limited',                    'ITC',         'NSE', 'Consumer Staples',       'FMCG & Hospitality'),
('JSW Steel Limited',              'JSWSTEEL',    'NSE', 'Materials',              'Steel'),
('Kotak Mahindra Bank Limited',    'KOTAKBANK',   'NSE', 'Banking',                'Private Sector Bank'),
('Larsen & Toubro Limited',        'LT',          'NSE', 'Industrials',            'Engineering & Construction'),
('Mahindra & Mahindra Limited',    'M&M',         'NSE', 'Automobiles',            'SUVs & Tractors'),
('Maruti Suzuki India Limited',    'MARUTI',      'NSE', 'Automobiles',            'Passenger Vehicles'),
('Nestle India Limited',           'NESTLEIND',   'NSE', 'Consumer Staples',       'Food Products'),
('NTPC Limited',                   'NTPC',        'NSE', 'Utilities',              'Power Generation'),
('Oil & Natural Gas Corporation',  'ONGC',        'NSE', 'Energy',                 'Oil & Gas Exploration'),
('Power Grid Corporation',         'POWERGRID',   'NSE', 'Utilities',              'Power Transmission'),
('Reliance Industries Limited',    'RELIANCE',    'NSE', 'Conglomerate',           'Oil & Gas / Telecom / Retail'),
('SBI Life Insurance Company',     'SBILIFE',     'NSE', 'Financial Services',     'Life Insurance'),
('Shriram Finance Limited',        'SHRIRAMFIN',  'NSE', 'Financial Services',     'NBFC'),
('State Bank of India',            'SBIN',        'NSE', 'Banking',                'Public Sector Bank'),
('Sun Pharmaceutical Industries',  'SUNPHARMA',   'NSE', 'Healthcare',             'Pharmaceuticals'),
('Tata Consultancy Services',      'TCS',         'NSE', 'Information Technology', 'IT Services'),
('Tata Consumer Products',         'TATACONSUM',  'NSE', 'Consumer Staples',       'Food & Beverages'),
('Tata Motors Limited',            'TATAMOTORS',  'NSE', 'Automobiles',            'Passenger & Commercial Vehicles'),
('Tata Steel Limited',             'TATASTEEL',   'NSE', 'Materials',              'Steel'),
('Tech Mahindra Limited',          'TECHM',       'NSE', 'Information Technology', 'IT Services'),
('Titan Company Limited',          'TITAN',       'NSE', 'Consumer Discretionary', 'Watches & Jewellery'),
('Trent Limited',                  'TRENT',       'NSE', 'Consumer Discretionary', 'Retail'),
('UltraTech Cement Limited',       'ULTRACEMCO',  'NSE', 'Materials',              'Cement'),
('Wipro Limited',                  'WIPRO',       'NSE', 'Information Technology', 'IT Services')
ON CONFLICT (ticker, exchange) DO NOTHING;
